apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-mock
  labels:
    appname: node-app-replicaset
    component: frontend
spec:
  selector:
    matchLabels:
      appname: node-app-replicaset
      component: frontend
  template:
    metadata:
      labels:
        appname: node-app-replicaset
        component: frontend
    spec:
      containers:
      - name: node-app
        image: 634809228531.dkr.ecr.us-east-1.amazonaws.com/db_mysql:v0.1
        ports:
        - containerPort: 8081