apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    appname: node-app
    component: frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    apname: node-app-deployment
    component: frontend