apiVersion: v1
kind: Service
metadata:
  name: node-app-replicaset
  labels:
    appname: node-app-replicaset
    component: frontend
spec:
  ports:
  - port: 8080
    targetPort: 8081
  selector:
    appname: node-app-replicaset
    component: frontend