apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    appname: node-app
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
  selector:
    appname: node-app
    component: frontend